version: '3'

services:
  syd_tp_001_ipsec_alice:
    container_name: syd_tp_001_ipsec_alice
    privileged: true
    build:
      context: './ALICE/'
    image: sydacademy/syd_tp_001_ipsec_alice
    stdin_open: true
    tty: true   
    restart: unless-stopped
    volumes: 
      - "./exchange/:/exchange_alice/"
    networks:
      syd_tp_001_ipsec_network:
        ipv4_address: 10.0.0.101

  syd_tp_001_ipsec_bob:
    container_name: syd_tp_001_ipsec_bob
    privileged: true
    build:
      context: './BOB/'
    image: sydacademy/syd_tp_001_ipsec_bob
    stdin_open: true
    tty: true
    restart: unless-stopped  
    ports:
      - 1194:1194/udp

    cap_add:
      - CAP_SYS_ADMIN   
      - NET_ADMIN 
    networks:
      syd_tp_002_ipsec_network:
        ipv4_address: 10.0.0.201
    volumes: 
      - "./exchange/:/exchange_bob/"

networks:
  syd_tp_001_ipsec_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.100/30
          gateway:  10.0.0.102

  syd_tp_002_ipsec_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.200/30
          gateway:  10.0.0.202
